### ISSUE TITLE
emoji color icons

### ISSUE THREAD

**Issue by lambdafu** [shd101wyy/markdown-preview-enhanced#1019]
In markdown-preview, unicode emojis (🍕) are rendered b/w and markdown emojis (`:pizza:`) are rendered in color (:pizza:). In markdown-preview-enhanced, either is rendered b/w. Would be nice to have color emoji font support.
This is on Linux. Thanks!

**Comment by Luk313** [comment]
+10!! Would be VERY NIVE!! It is such a pity, that currently markdown emojis' exports :+1: 
* in HTML (via markdown-preview-enhanced) are rendered correctly in color, but 
* not even rendered in PDF (via Chrome Puppeteer). 
Also Linux here (Manjaro Linux). Many thanks by advance if you could do something for us

**Comment by d3vr** [comment]
I'm on linux as well, and I had the same issue. Figured out a work around. You need to add an emoji font to the preview (doesn't take the Editor font family into account). So just `Ctrl+P` and select `Markdown Preview Enhanced: Customize CSS` and add a `font-family` property:
```css
.markdown-preview.markdown-preview {
  font-family: "Helvetica Neue",Helvetica,"Segoe UI",Arial,freesans,sans-serif, 'Noto Color Emoji';
}
```
`Noto Color Emoji` is the emoji font in my case.

PS: You can use the developer tools to find out which font(s) were being used by the preview so you can maintain that and add the emoji font (`Help menu > Toggle Developer Tools`)
