### ISSUE TITLE
Headers/Footers on PDF!

### ISSUE THREAD

**Issue by chiarld** [shd101wyy/markdown-preview-enhanced#1028]
Hello!

How's it going?

Just a callback for issue #57, is there any way to have headers/footers for exporting to PDF now? For this specific document, I plan to export with Pandoc but it would be useful to have it for Puppeteer too.

Thanks!

**Comment by shd101wyy** [comment]
https://shd101wyy.github.io/markdown-preview-enhanced/#/puppeteer?id=configure-puppeteer

this?

**Comment by chiarld** [comment]
Hey, I'm not sure I completely understand. Are you saying I would have to edit the CSS to make something header/footer-like?

I just wanted something like this:
![Headers and Footer Pandoc](https://i.stack.imgur.com/rUC8t.png)

^ For Pandoc.

Thanks in advance.

**Comment by shd101wyy** [comment]
i am not sure how to add headers&footers for pandoc export, but for
puppeteer export i just write header and footer configs in puppeteer
frontmatter.

**Comment by chiarld** [comment]
Would it be something like?
```
puppeteer:
    header: "text/html"
    footer: "text/html"
```

**Comment by shd101wyy** [comment]
yes
use headerTemplate and footerTemplate
click the PDF link to see the details.

**Comment by chiarld** [comment]
Alright, after working around a bunch of weird bugs I figured out a way to have headers/footers.

For future reference, you can just do:
```
---
puppeteer:
    headerTemplate: '<div style="width:100%; text-align:right; border-bottom: 1pt solid #eeeeee; margin: -10px 20px 0; font-size: 8pt;"><p><YOUR HEADER></p></div>'
    footerTemplate: '<div style="width:100%; text-align:right; border-top: 1pt solid #eeeeee; margin: 0 20px -10px 0; font-size: 8pt">< YOUR FOOTER></div>'
    displayHeaderFooter: true
    margin:
      top: '15mm'
      bottom: '15mm'
---
```

1. `width: 100%` is necessary to align text to the right.
1. `font-size: <a size>` is necessary. For some reason the default is 0pt.
1. Margins for top and bottom are necessary. Otherwise, the document will just display over your header/footer. 
1. displayHeaderFooter is also necessary. You can probably guess what happens otherwise.

Here is how it looks after you export to PDF with puppeteer:

<img width="555" alt="headerandfooter" src="https://user-images.githubusercontent.com/39843321/48972510-a8e39500-efe0-11e8-8edf-21f9d7c9dd5d.png">

Feel free to add this to the docs if you'd like. I think other people mind find it helpful. 

Also, thanks a lot for the help! Closin the issue 😉
