### ISSUE TITLE
markdown table render problem when update to 0.8.1

### ISSUE THREAD

**Issue by maplewizard** [shd101wyy/markdown-preview-enhanced#106]
I have a markdown table:

| 啊啊啊 | 啊啊啊 |
| --- | --- |
| 啊啊啊，啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊 | 是是是 |

but it render like this:
![image](https://cloud.githubusercontent.com/assets/1419566/17663866/6c17d390-6322-11e6-9385-55d6230a78a0.png)

**Comment by shd101wyy** [comment]
It seems to be a css bug. 
Right now you can fix it by `Markdown Preview Enhanced: Customzie Css` then add the code below to `.markdown-preview-enhanced-custom` section.

```less
  td {
    // overflow: auto;
    // or
    word-break: break-all;
  }
```

I will fix this issue in next version.
