### ISSUE TITLE
CSS adjacent sibling combinator not working in atom preview

### ISSUE THREAD

**Issue by jacoping** [shd101wyy/markdown-preview-enhanced#1061]
Hi! I discovered that in Atom preview CSS adjacent sibling combinator seems to be not workings.
For example, with this less code

``` less
.markdown-preview.markdown-preview {
  h1 + h2 { color: red; }
}
```

and this markdown

```md
#Title
## First heading
Some text
## Second heading
Some other text
```
the resulting preview does not shows "First heading" in red.

It is important to note that if I open the preview in the browser the compiled html is correct and visualize properly showing "First heading" in red.

Is there something wrong in my less code?
I also tried a maybe more accurate version of the less code:
```less
.markdown-preview.markdown-preview {
	h1 {
		&+h2 {
			color: red;
		}
	}
}
```
but it still does not visualize properly in Atom preview.

Thanks!
Jacopo
