### ISSUE TITLE
customize CSS 的修改没作用到预览

### ISSUE THREAD

**Issue by siriuscc** [shd101wyy/markdown-preview-enhanced#1073]
我自定义了一些css 在style.css,然后在插件对应的预览窗口中并不能完全显示出这些css控制的效果。他只完成了我对颜色的修改；对img图标的display和::after 则没有作用到；

而右键预览窗口->在浏览器中打开，则这些css样式都作用到了。

```css
.markdown-preview.markdown-preview {
  // modify your style here
  // eg: background-color: blue;  

  p>code,li>code{
    background: #ffebeb;
    color: #c7254e;
    border-radius: 3px;
    border: 1px;
  }

  img{
    margin: 0 auto;
    display: block;
  }

  img::after{
    content:attr(alt);
  }

  span.s-img-alt{
    display: inline-block;
    margin: 0 auto;
    line-height: 1.7;
    font-size: 14px;
    color: #969696;
    border-bottom: 1px solid #d9d9d9;
    padding: 10px;
  }
}

```
![预览](https://user-images.githubusercontent.com/16629888/53690340-86150980-3da3-11e9-8541-ae53daaeae9d.png)

![预览 ](https://user-images.githubusercontent.com/16629888/53690332-5ebe3c80-3da3-11e9-8f2d-48fbd97bcb2d.png)

![浏览器](https://user-images.githubusercontent.com/16629888/53690336-73023980-3da3-11e9-91be-f1c03e70fb37.png)
