### ISSUE TITLE
export_on_save for puppeteer

### ISSUE THREAD

**Issue by kunanit** [shd101wyy/markdown-preview-enhanced#1087]
It would be great to be able to automatically export on save for [Puppeteer](https://shd101wyy.github.io/markdown-preview-enhanced/#/puppeteer) using the `export_on_save` option in the front matter, similarly to the functionality available for phantomJS, pandoc, etc.

I didn't see it explicitly mentioned in the docs so I'm assuming it is not currently available, but If this is already possible through this or some other syntax I'd be interested to know!

e.g. something like
```yaml
---
export_on_save:
    puppeteer: true
---
```
or
```yaml
---
export_on_save:
    puppeteer: "pdf"
---
```
