### ISSUE TITLE
请问如何修改粗体文字的 css 样式?

### ISSUE THREAD

**Issue by RockyAstor** [shd101wyy/markdown-preview-enhanced#1145]
如题, 谢谢!

使用如下 css 貌似无效?
```css
  bold {
    color: #d8dee9;
  }
```

**Comment by shd101wyy** [comment]
是 `strong`：

```less

.markdown-preview.markdown-preview {
  // modify your style here
  // eg: background-color: blue;
  strong {
    color: #d8dee9;
  }
}
```
