### ISSUE TITLE
How to center the H1 title ?

### ISSUE THREAD

**Issue by meteorsh** [shd101wyy/markdown-preview-enhanced#1325]
First, I want to thanks for the great work you're doing 👍

I was trying to center the title but I don't know the syntax. Can you help me?

```
.markdown-preview.markdown-preview {
	// modify your style here
	// eg: background-color: blue;
  font-size: 19px;
  // font-family: "Consolas";
	font-family: "新宋体";

	h1 {
		border-bottom: 1.5px solid #999999;
    font-family: "微软雅黑";
    font-size: 30px;
  }
  h2 {
    font-size: 24px;
  }
  h3 {
    font-size: 22px;
  }
}
```

![image](https://user-images.githubusercontent.com/46078304/77129645-afc4cf80-6a8f-11ea-8ee0-76c1a798ab12.png)

 **Environment**

- Operating system : macOS Majave Version 10.14.5
- Chrome : Version 80.0.3987.132
- VScode:  Version 1.43.1

**Comment by meteorsh** [comment]
And another problem for me is can I delete this dot in the toc
![image](https://user-images.githubusercontent.com/46078304/77137666-cf68f180-6aa9-11ea-8e6c-ccf80f5c08fe.png)

**Comment by zcysxy** [comment]
文字居中是 `text-align: center`, 如下

```css
h1 {
    text-align: center;
    border-bottom: 1.5px solid #999999;
    font-family: "微软雅黑";
    font-size: 30px;
  }
```

我的理解 MD 的 TOC 就是一个带链接的无序列表, 所以一般你只能所有无序列表都有 bullets 或者都没有. 所有无序列表都没有 bullet 的话跟改变 h1 样式差不多插入下面的就好:

```css
ul {
    list-style-type: none;
}
```
