### ISSUE TITLE
Sidebar TOC in html export no longer available

### ISSUE THREAD

**Issue by marclang** [shd101wyy/markdown-preview-enhanced#1359]
Hi, 

I used Atom 1.43 and I recently update markdown-preview-enhanced to 0.17.8 version. 

I used to set the following yalm header for html export : 

```
---
export_on_save:
  html: true
html:
  toc: true

print_background: true
---
```

However, the sidebar TOC in html export no longer available since I update the extension in atom. Is the feature no longer supported ? 

Thanks !
