### ISSUE TITLE
E-Book export exception on empty list elements

### ISSUE THREAD

**Issue by rkaradas** [shd101wyy/markdown-preview-enhanced#136]
Hi, first of all great job!
I found a small issue, when exporting as e-book. 
I get an exception, if a list element begins and no text follows. Take a look at the provided Markdown below (last line).

And here is the relevant part of the exception:
TypeError: Cannot read property 'getElementsByTagName' of undefined
    at getStructure (file:///..../markdown-preview-enhanced-view.coffee:1170:29)

Steps to reproduce:
1. Copy the provided markdown and paste into local md file
2. Open md preview enhanced and right-click->export to disk
3. Select ebook and click export 

```
---
ebook:
  title: e-book export issue
  author: Recep Karadas
---
# Test

- list element 1
- list element 2
- list element 3
-
```
