### ISSUE TITLE
Is there any way to tweak the MathJax css settings?

### ISSUE THREAD

**Issue by zelhar** [shd101wyy/markdown-preview-enhanced#142]
Hi. I am trying to change the color of the mathjax formulas to make them stick out from the text. I tried to add this part to the matjax-wrapper.coffee but it doesn't work. Is there any other way to change this setting?

```
MathJax.Hub.Config({
....  
        styles: {
            ".MathJax_Preview": {
              color: "blue"
            },
            ".MathJax": {
              color: "blue"
            },
})
```

**Comment by shd101wyy** [comment]
Hi @zelhar ,

You can run `Markdown Preview Enhanced: Customzie Css` command, it will open `style.less` for you and automatically generate a section called `.markdown-preview-enhanced-custom`.  
Then you can edit like this:   

```less
.markdown-preview-enhanced-custom {
  .MathJax {
    color: blue;
  }
}
```

**Comment by zelhar** [comment]
Thank you @shd101wyy, this does the trick.
Do you know perhaps if it can also be done with KaTX?

**Comment by shd101wyy** [comment]
Yes of course.

```less
  .katex {
    color: blue;  
  }

```
