### ISSUE TITLE
Export to PDF with Puppeteer doesn't render any math

### ISSUE THREAD

**Issue by DavidJLu** [shd101wyy/markdown-preview-enhanced#1516]
Exporting to PDF using Puppeteer doesn't render any math. Everything else is fine. Exporting to PNG or JPEG with Puppeteer work as well.

**Comment by shd101wyy** [comment]
You could try increase the timeout before printing

https://shd101wyy.github.io/markdown-preview-enhanced/#/puppeteer?id=configure-puppeteer

```yaml
puppeteer:
  landscape: true
  format: "A4"
  timeout: 3000 # <= Special config, which means waitFor 3000 ms
```
