### ISSUE TITLE
Change CSS Width in Browser Preview

### ISSUE THREAD

**Issue by tecunningham** [shd101wyy/markdown-preview-enhanced#1548]
I don't know how to over-ride the CSS text-width in the browser preview.

The following CSS will change body width for HTML *exports*:

```css
html body[for="html-export"]:not([data-presentation-mode]) { width: 55%; }
```

However I haven't found a way of changing the width for *in-editor* previews. The following doesn't work:

```css
html body[for="preview"]:not([data-presentation-mode]) { width: 55%; }
```

(Context: I'm adapting CSS from https://github.com/edwardtufte/et-book/blob/gh-pages/et-book.css , which has 55% body width, so it can have notes in the margin).
