### ISSUE TITLE
How to add a vertical scroll bar to the code?

### ISSUE THREAD

**Issue by PengWei97** [shd101wyy/markdown-preview-enhanced#1562]
Considering that the code module inserted in markdown in vs code is too long, how can I set it up to add a vertical scroll bar?

**Comment by electronum** [comment]
* In General, this is controlled by CSS property `overflow-y` [Explanation on Stack Overflow](https://stackoverflow.com/questions/9707397/making-a-div-vertically-scrollable-using-css/9707674)
* You could adjust your `style.less` (see [Extension Manual](https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css) )
*  Example: I set `overflow-y: scroll` and `height: 100px;` to force scrolling
* `pre[class*="language-"]` enables that for all code samples, otherwise you just have to play with CSS class names 
*  For example, `pre.language-javascript` would be enough for Java Script
```css
.markdown-preview.markdown-preview {
  // modify your style here
  // eg: background-color: blue;

  pre[class*="language-"] {
    height: 100px;
    overflow-y: scroll;
  }
}
```
* Reason: the generated HTML for code samples looks like this 
```html
<pre data-role="codeBlock" data-info="js" class="language-{language-x}">
...
</pre>
```
