### ISSUE TITLE
Pandoc keeps saying 'Error: Output format needs to be specified.'

### ISSUE THREAD

**Issue by MartinDrenth** [shd101wyy/markdown-preview-enhanced#1608]
Hi Yiyi Wang
First of all, you're my hero. Great work you have done on the markdown-previewer

I have some trouble with the `Pandoc` feature. I have added the FrontMatter stuff in the top of the .md file:
```
---
lastmod: '2021-08-12T13:34:37.771Z'
output:
    word_document:
        reference_doc: 'C:\Users\marti\Documents\PandocreferenceUK.docx'
date: '2021-08-12T13:34:37.770Z'
---
```

but for an unknown reason the pandoc feature says `'Error: Output format needs to be specified.'`

If I create a _new_ .md file and copy the exact same contents, it does work. 
Can you explain this?
