### ISSUE TITLE
No images generated from diagrams

### ISSUE THREAD

**Issue by janebrain** [shd101wyy/markdown-preview-enhanced#1637]
I am attempting to use the "Save to Markdown" feature when right-clicking the preview. Sequence and Flow diagrams appear properly in the preview, but the output markdown contains the source markdown used to generate them rather than references to any images. I have indicated a relative path for the images, and a folder with the matching name is created, but remains empty. I am using the following front-matter if it's relevant.
```
---
export_on_save:
  markdown: true
markdown:
  path: output.md
  imageFolderPath: /markdown_assets
  ignore_from_front_matter: false
  absolute_image_path: false
---
```
