### ISSUE TITLE
Is it possible to make the output graph of Code Chunk centralised?

### ISSUE THREAD

**Issue by thelxz** [shd101wyy/markdown-preview-enhanced#1644]
It seems that **align="center"**  not working for **Code Chunk** graphs. Any workaround?
for example graph of gnuplot:
```markdown
    ```gnuplot {cmd=true output="html" hide align="center"}
    set terminal svg
    set title "Simple Plots" font ",20"
    set key left box
    set samples 50
    set style data points
    plot [-10:10] sin(x),atan(x),cos(atan(x))
    ```
```

**Comment by shd101wyy** [comment]
@thelxz `ctrl-shift-p` then run `Markdown Preview Enhanced: Customize CSS` command to open the `style.less` file. Then add the following css:

```less
.markdown-preview.markdown-preview {
  // modify your style here
  // eg: background-color: blue;

  .output-div {
    text-align: center;
  }
}
```
