### ISSUE TITLE
Preview for more variables in pandoc yaml metadata block

### ISSUE THREAD

**Issue by ithotuwanted2dance** [shd101wyy/markdown-preview-enhanced#1673]
The pandoc parser for live preview does not display some fairly basic variables that one would typically include in the yaml metadata block.  For example, none of the following display at all in the live preview 

```yaml
---
title: Pandoc Notes
author:
- Some Person
- Some Other Person
abstract: |
  This is the abstract.

  It consists of two paragraphs.
---
```
This is related to #1570.
