### ISSUE TITLE
Unknown paragraph's bottom margin when I custom css

### ISSUE THREAD

**Issue by HxxWorkAccount** [shd101wyy/markdown-preview-enhanced#1702]
In the beginning, I wanted to use plantuml, which is a very powerful tool.
But I found that if the plantuml is too big, it will break the right side border and make the preview scroll horizontally.

<img width="694" alt="Snipaste_2022-05-13_14-31-03" src="https://user-images.githubusercontent.com/99344391/168224652-d238d3d2-b1e5-4936-b2f7-02cf14b176bc.png">

So I checked the html code and found that the svg generated by plantuml is placed directly under \<p\>. Then I wrote this code in the custom css:
```css
p {
  margin: 16px 0px 0px 0px !important;
  padding: 0 0 0 0 !important;
  overflow-x: auto;
  overflow-y: hidden;
}
p::-webkit-scrollbar {
  height: 0;
  width: 0;
}
```

This code **works perfectly in Chrome and Safari**, but in Preview it cause unknown bottom margin under the paragraph element.

example:

Before adding css code:
<img width="696" alt="Snipaste_2022-05-13_14-35-23" src="https://user-images.githubusercontent.com/99344391/168225373-24a62fbf-9112-4d85-b223-06e33ad5be68.png">

After adding css code:
<img width="696" alt="Snipaste_2022-05-13_14-36-32" src="https://user-images.githubusercontent.com/99344391/168225442-af78842c-289a-4581-8abb-69115fcff776.png">

Obviously this is not a very important issue and the author may not have time to fix it, but I'd still like to know if there is an easy fix. Or maybe some other ways to help overflow svg scroll inside \<p\> which will prevent preview from appearing scrollbar. ₍ᐢ •͈ ༝ •͈ ᐢ₎♡

BTW, check out my custom style full text [here](https://github.com/HxxWorkAccount/Markdown-Google-Style).
