### ISSUE TITLE
预览界面字太大，如何调小

### ISSUE THREAD

**Issue by zhouyuling0317** [shd101wyy/markdown-preview-enhanced#1745]
在vs code里下载了markdown preview enhanced，写了文字，打开预览，预览界面的字太大了，不像markdown preview enhanced介绍页面那样，字的大小合适，如何调整？
![1665563513397](https://user-images.githubusercontent.com/115620819/195292536-82426ad4-79f8-47cc-922b-a041acf7bec8.png)

**Comment by Dunky-Z** [comment]
`Ctrl+Shift+P`打开运行窗口，输入`Markdown Preview Enhanced: Customize Css`打开`style.less`，编辑CSS文件可以实现。例如
```css

.markdown-preview.markdown-preview {
  // modify your style here
    @page {
        font-size: 12pt;
      }
      h1 {
           font-size: 40px;
      }
      h2 {
        font-size: 30px;
      }
      h3 {
        font-size: 20px;
      }
      h4 {
        font-size: 16px;
      }
}
```
其他定制内容可以学习一下CSS。
