### ISSUE TITLE
分享Chrome (Puppeteer) 导出增加页眉页脚方法

### ISSUE THREAD

**Issue by Gsonovb** [shd101wyy/markdown-preview-enhanced#1770]
页面中添加如下内容，开启页眉页脚输出
```
---
puppeteer:
  format: "A4"
  displayHeaderFooter: true
  footerTemplate: '<div style="font-size: 8px; font-weight: 400; padding: 3px; border-top: solid lightgray 1px;text-align: center; width: 100%;"><span class="pageNumber"></span>/<span class="totalPages"></span></div>'
  headerTemplate: '<div style="font-size: 8px; font-weight: 400; padding: 3px; border-bottom: solid lightgray 1px;text-align: center; width: 100%;"><span class="title"></span></div>'
  margin: 
    bottom: 15mm
    left: 20mm
    right: 20mm
    top: 15mm
  timeout: 3000 # <= 特殊设置，意味着等待（waitFor） 3000 毫秒
---
```

https://gist.github.com/Gsonovb/a80efa48bfa3c509284e84916c9335d3
