### ISSUE TITLE
broken table of contents links when using pandoc parser

### ISSUE THREAD

**Issue by mcaruel** [shd101wyy/markdown-preview-enhanced#1772]
Hi,
The table of contents generated with pandoc parser should contain links redirecting to the sections corresponding to the table entries. These links are not working. The links appearing in the menu § are also broken when using the pandoc parser.

Note that the links towards the list of reference are working.

Here are my settings:
```json
"markdown-preview-enhanced.usePandocParser": true,
    "markdown-preview-enhanced.pandocArguments": [
        // "--citeproc",
        // "tex_macros.tex",
        "--defaults=../static/pandoc-config.yaml",
        "--standalone"
    ],
"markdown-preview-enhanced.pandocMarkdownFlavor": "markdown+tex_math_single_backslash+footnotes+citations+fancy_lists+latex_macros",
```

the content of the pandoc-config.yaml is 
```
filters:
  - pandoc-xnos
  - citeproc
  # - type: json
    # path: pandoc-xnos
  # - type: citeproc
  # - crossref
metadata:
  author: blabla
  lang: en-US
  bibliography: path_to_bib
  citation-style:path_to_style
  link-citations: true
  linkReferences: true
  crossrefYaml: pandoc-crossref.yaml
cite-method: biblatex
number-sections: false
number-offset:
- 6
table-of-contents: true
```
