### ISSUE TITLE
How to Specify Font Size for Particular Slide?

### ISSUE THREAD

**Issue by thiner** [shd101wyy/markdown-preview-enhanced#257]
I am using the MPE to write a slides. I have some code sample to show in one of the slides. However, some of them become invisible due to the default font size is too large. If set the font-size to 14px, that would be solved. I know we can modify the style.css file to change the font-size. But I don't want to change it for all slides. How to specify the custom font-size for the slide?
我在用MPE插件写一个演讲稿。其中有一页有比较长的代码展示。但是由于默认字体太大，后面有一部分被遮住了。如果可以把这一页的字体单独设置成14px就很完美了。怎么做？

**Comment by shd101wyy** [comment]
Hi @thiner ,

你可以 `cmd+shift+p` 然后运行 `Markdown Preview Enhanced: Customize Css` 命令，
在 `.markdown-preview-enhanced-custom` 内部添加如下代码:

```less
.markdown-preview-enhanced-custom {
  // ...
  // change the font size of the second slide to 14px
  .slide:nth-child(2),
  &[data-presentation-mode] section:nth-child(2) {
    font-size: 14px;
  }
}
```

**Comment by thiner** [comment]
非常感谢，这招管用。
在此基础之上，我加了一些额外的CSS来显示一个带有公司logo的脚注，放在这里一并分享，给有需要的人。
Thanks a lot! It works. 
I made some other changes in this way to show a footer image for every slides. I'd like to share it here for someone else who may need it. 
```css
  @orange: rgb(230, 84, 0);
  @gold: rgb(250, 182, 54);
  @footer-img: no-repeat url(assets/orn_rgb_pos.png) bottom left;

  .preview-slides .slide,
  &[data-presentation-mode] {
    font-size: 18px;
    h1 {
      color: @orange;
      font: 48px arial bold, sans-serif;
    }
    h2 {
      color: @gold;
      font: 24px arial bold, sans-serif;
    }
    .slide-background {
      background: @footer-img;
      background-size: 8%; // I'm using a very large image, so I need to specify a smaller size here
    }
    .slide-background:last-child {
      display: none;
    }
  }
```
