### ISSUE TITLE
References in preview

### ISSUE THREAD

**Issue by adamaltmejd** [shd101wyy/markdown-preview-enhanced#315]
Is there any way to get references (through pandoc-citeproc) to show up in the preview?

**Comment by shd101wyy** [comment]
Hi @adamaltmejd , 

No there isn't. Markdown has its own support for references. For example:

```markdown 
Content [^1]
[^1]: abc: XXXX
```

Thanks

**Comment by adamaltmejd** [comment]
Ah, those are footnotes, but I'm talking about a reference system with bib files as the one pandoc-citeproc supports. Using Markdown Preview Plus with Atom right now and that's a pretty important feature to me. I guess the problem is that you are not using pandoc as a parser for the previews? Maybe it would be possible to add an option for enabling pandoc-citeproc to process references (for example if its specified in the YAML header)?

**Comment by shd101wyy** [comment]
I see what you mean. I will check `markdown-preview-plus`.  
Could you please also attach a sample file and show me how the preview should look like?  
Thank you

**Comment by adamaltmejd** [comment]
How pandoc does it is well described in the manual here: http://pandoc.org/MANUAL.html#citations and the pandoc-citeproc MAN page: https://github.com/jgm/pandoc-citeproc/blob/master/man/pandoc-citeproc.1.md

Here is a MWE

```
---
references:
- id: doe2006
  author:
    family: Doe
    given: [John, F.]
  title: Article
  page: 33-34
  issued:
    year: 2006
  type: article-journal
  volume: 6
  container-title: Journal of Generic Studies
---

# Example
@doe2006 says blah.

# References
```
