### ISSUE TITLE
Pagebreaking on tables in PDF Export

### ISSUE THREAD

**Issue by BrekiTomasson** [shd101wyy/markdown-preview-enhanced#335]
First of all; I'm absolutely loving this package; it's increased my productivity as regards documentation tenfold.

Just one problem, though. I use a lot of tables in my technical documentation, and when exporting Markdown to PDF I often encounter pagebreaks before a table if that table were to span from one page and into the other. This often leads to massive whitespace on a page followed by a table on a new page. Would it be possible to have some sort of toggle to avoid this?

**Comment by shd101wyy** [comment]
Hi @BrekiTomasson 

This can be solve by running `Markdown Preview Enhanced: Customize Css` command, then edit as the following:  

```less
.markdown-preview-enhanced.markdown-preview-enhanced {
  @media print {
    table {
      page-break-inside: auto;
    }
  }
}
```

Thanks
