### ISSUE TITLE
 图片居中和标题下划线的问题

### ISSUE THREAD

**Issue by simoxi** [shd101wyy/markdown-preview-enhanced#360]
请问如何设置styles.less 文件让图片居中和在图片的正下方显示图片的标题？
怎么删除标题的下划线？比如我想取消H2标题的下划线。。。
其他的一些详细更改是否和其他markdown修改css文件格式一样呢？

**Comment by shd101wyy** [comment]
Hi @simoxi 
运行 `Markdown Preview Enhanced: Customize Css` 然后修改 `style.less`

```less
.markdown-preview-enhanced.markdown-preview-enhanced {
    h1, h2, h3, h4, h5, h6 {
        text-decoration: none: // 取消下划线
    }
}
```

谢谢

**Comment by simoxi** [comment]
不管用啊。。。。none后面的是分号吧。。。改了也不管用啊。。。

**Comment by shd101wyy** [comment]
把你的 style.less 发给我看看。

**Comment by simoxi** [comment]
```
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */


/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// style UI elements inside atom-text-editor
atom-text-editor .cursor {
//   border-color: red;
}


/*
 * markdown-preview-enhanced custom style
 */
.markdown-preview-enhanced.markdown-preview-enhanced {
font-family: Microsoft Yahei UI;  //change font formate

  // please write your custom style here
  // eg:
  //  color: blue;          // change font color
  p {
    color: rgb(47,66,83)
  }
  h1, h2, h3, h4, h5, h6 {
        color: rgb(44,63,81);
        test-decoration: none;
      }
    color: rgb(44,63,81);
    font-size: 20px;
    font-family: Microsoft YaHei;
  //

  // custom pdf output style
  @media print {

  }

  // custom prince pdf export style
  &.prince {

  }

  // custom phantomjs png/jpeg export style
  &.phantomjs-image {

  }

  //custom phantomjs pdf export style
  &.phantomjs-pdf {

  }

  // custom presentation style
  .preview-slides .slide,
  &[data-presentation-mode] {
    // eg
    // background-color: #000;
  }
}
``` #

**Comment by shd101wyy** [comment]
哦我的，你这么写:

```less
.markdown-preview-enhanced.markdown-preview-enhanced {
  // 取消下划线
  h1, h2, h3, h4, h5, h6 {
    border-bottom: none;
  }

  // 图片居中
  img {
    position: relative;
    left: 50%;
    transform: translateX(-50%);
  }
}
```

关于添加图片的标题，这个是 markdown parser 的问题，默认的 remarkable 没有添加标题。
你可以在插件设置中换用 pandoc parser。
