### ISSUE TITLE
YAML代码之后的语法渲染有问题

### ISSUE THREAD

**Issue by deathrush** [shd101wyy/markdown-preview-enhanced#370]
yaml没有语法高亮

    ```YAML
    ---
    - hosts: webservers
      vars:
        http_port: 80
        max_clients: 200
      remote_user: root
      tasks:
      - name: ensure apache is at the latest version
        yum: pkg=httpd state=latest
      - name: write the apache config file
        template: src=/srv/httpd.j2 dest=/etc/httpd.conf
        notify:
        - restart apache
      - name: ensure apache is running
        service: name=httpd state=started
      handlers:
        - name: restart apache
          service: name=httpd state=restarted
    ```
