### ISSUE TITLE
[BUG] Update Button rendered outside of the preview window and hid itself on mouse over when showing some tool-bars.

### ISSUE THREAD

**Issue by tmori3y2** [shd101wyy/markdown-preview-enhanced#402]
I tried the following procedures.

* installs markdown-writer
* installs tool-bar
* installs tool-bar-main
* installs tool-bar-markdown-writer

Then Update Button rendered outside of the preview window and hid itself on mouse over.

Best Regards.

**Comment by tmori3y2** [comment]
tool-bar settings

icon size: 24 px

position: top

and only tool-bar-main is displayed.

<img width="911" alt="2017-05-17 1" src="https://cloud.githubusercontent.com/assets/18054170/26132338/9fa9b18e-3ada-11e7-8f45-d7a93aeff0ed.png">

Now I set the position to 'left' to avoid this issue.

Best Regards.

**Comment by shd101wyy** [comment]
@tmori3y2 quick fix for this problem:

`cmd+shift+p` then choose `Markdown Preview Enhanced: Customize Css` then edit `.markdown-preview-enhanced.markdown-preview-enhanced` section like below:

```less
.markdown-preview-enhanced.markdown-preview-enhanced {
  font-size: 1.2em;

  .back-to-top-btn, .refresh-btn {
    top: 200px; // top pos you want; change to whatever you want.  
  }
// ...
}
```
