### ISSUE TITLE
Preview scaling

### ISSUE THREAD

**Issue by gmd7** [shd101wyy/markdown-preview-enhanced#404]
Is it possible to scale the preview Window? I have to use different display resolutions and on sometimes the font is too small.

**Comment by shd101wyy** [comment]
`Markdown Preview Enhanced: Customize Css`, then edit `.markdown-preview-enhanced.markdown-preview-enhanced` section like this:  

```less
.markdown-preview-enhanced.markdown-preview-enhanced {
  font-size: 24px; // how big you want your font to be.
}
```
