### ISSUE TITLE
#标题下面的分隔符如何去除啊

### ISSUE THREAD

**Issue by Mrdshu** [shd101wyy/markdown-preview-enhanced#458]
我看官方文档里面#生成的标题下面是没有分隔符的，但我现在使用#却生成了分隔符。
看的太难受了，请问这个能修改掉吗？
![image](https://user-images.githubusercontent.com/15122045/27250544-4e389542-5365-11e7-8971-24b15f69c456.png)

**Comment by shd101wyy** [comment]
`Markdown Preview Enhanced: Customize Css` 然后编辑 `style.less`。

```less
.markdown-preview-enhanced.markdown-preview-enhanced {
    h1, h2, h3 {
        border-bottom: none;
    }
}
```
