### ISSUE TITLE
Question or New Feature Request: Multiple pandoc output support

### ISSUE THREAD

**Issue by gepcel** [shd101wyy/markdown-preview-enhanced#467]
How can I have multiple pandoc output at the same time like:
```yaml
---
output: [word_document, pdf_document]  # or
output:
    word_document:
    pdf_document:
---
```

Or with more options: 
```yaml
---
output:
    word_document:
        path: /output.docx
    pdf_document:
        path: /output.pdf
---
```
