### ISSUE TITLE
Feature Request: Local Styles for presentations

### ISSUE THREAD

**Issue by szacchino** [shd101wyy/markdown-preview-enhanced#481]
Hi shd,

I think that local CSS/SASS also for presentations would be a useful feature missing in this package. With this feature the presentation folder could be shared with others without doing copy/paste of MPE private sass.

Thanks again for you amazing project

**Comment by shd101wyy** [comment]
@szacchino I have just rewrote the presentation part, now it follows strictly how reveal.js defines its styles. Please check [customize css](https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css) and [presentation writer](https://shd101wyy.github.io/markdown-preview-enhanced/#/presentation).

**Comment by dzmitryv** [comment]
@shd101wyy When I try to change font size (e.g. font-size:8px;), it looks like it doesn't affect markdown preview in Atom but if I choose "Open in Browser" from the right-click menu and view the preview in a browser, the font size is changing in the browser. Also, the font size in the menu is affected by my changes...but not the markdown preview text. Any ideas why the font size could not change in the preview?

**Comment by shd101wyy** [comment]
@dzmitryv Can you show me the code of your style?

**Comment by dzmitryv** [comment]
Here is what I have in style.less:
`
html body {
  // modify your style here
  // eg: background-color: blue;
  font-size:8px;
}`

**Comment by shd101wyy** [comment]
@dzmitryv write it as 

```
html body {
  .reveal { // <= you need this class.
    font-size: 12px;
  }
}
```

**Comment by dzmitryv** [comment]
I tried this:
```css
html body {
  .reveal { // <= you need this class.
    font-size: 8px;
    background-color: blue;
  }
}
```

It didn't change the font size nor the background color. Just for comparison, the code below at least changes the background color (but doesn't affect font also).
```css
html body {
  background-color: blue;
  font-size:8px;
}
```

I'm not sure if it's important, I'm using Linux version of Atom.

**Comment by shd101wyy** [comment]
@dzmitryv which `style.less` file are you modifying? The one opened by the `Markdown Preview Enhanced: Customize Css` command?

**Comment by dzmitryv** [comment]
Yes, the one opened by that command. It opens ~/.mume/style.less

**Comment by shd101wyy** [comment]
@dzmitryv 
I think I need more information. Which operating system are you using? Which version of this package and atom are you using? Which Revealjs Theme are you using?

**Comment by shd101wyy** [comment]
It worked well on my Mac.

**Comment by dzmitryv** [comment]
`.slide` doesn't help also.
Here is the code that I tried:
```css
html body {
  // modify your style here
//  background-color: blue;
  font-size:8px;
  .slide { // <= you need this class.
    font-size: 8px;
    background-color: blue;
  }
}
```
I'm using: 14.04.1-Ubuntu
```
 $ atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
markdown-preview-enhanced 0.14.3
RevealJS theme: white.css

**Comment by shd101wyy** [comment]
Then I don't know why it doesn't work. I don't have a Linux machine so I am
not able to test it. I recommend you to open in browser then check the HTML
element structures and then try to modify the CSS according to the class of
elements.

**Comment by shd101wyy** [comment]
Add !important after the value.

**Comment by dzmitryv** [comment]
Like this?
```css
html body {
  // modify your style here
//  background-color: blue;
  font-size:8px!important;
  .reveal { // <= you need this class.
    font-size: 8px!important;
    background-color: blue;
  }
  .slide { // <= you need this class.
    font-size: 8px!important;
    background-color: blue;
  }
}
```
Didn't work :(

> I recommend you to open in browser then check the HTML
element structures and then try to modify the CSS according to the class of
elements.

That's the interesting part - in browser the font size changes depending on what value I use in font-size.

Thank you for looking into this and for the package in general!

**Comment by shd101wyy** [comment]
@dzmitryv 

```less
html body {
  // modify your style here
//  background-color: blue;
  font-size:8px !important;
  .reveal { // <= you need this class.
    font-size: 8px !important;
    background-color: blue;
  }
  .slide { // <= you need this class.
    font-size: 8px !important;
    background-color: blue;
  }
}
```

**Comment by shd101wyy** [comment]
I think this should work, I am 100% sure: 

```less
html body {
  .reveal .slides .slide {
    font-size: 12px !important;
  }
}
```

**Comment by dzmitryv** [comment]
Tried this one:
```
html body {
  .reveal .slides .slide {
    font-size: 12px !important;
  }
}
```
and this
```
html body {
  // modify your style here
//  background-color: blue;
  font-size:8px !important;
  .reveal { // <= you need this class.
    font-size: 8px !important;
    background-color: blue;
  }
  .slide { // <= you need this class.
    font-size: 8px !important;
    background-color: blue;
  }
}
```
Nope, didn't work :(

**Comment by shd101wyy** [comment]
Show me a screenshot plz.

**Comment by shd101wyy** [comment]
If I guess correctly, you closed your markdown file while editing the `style.less` file. You need to keep it open. Otherwise the preview will be disconnected and no updates would happen.

**Comment by dzmitryv** [comment]
No, I didn't close the markdown file while editing the `style.less`.

Here is the screenshot:
![screenshot](https://user-images.githubusercontent.com/22772760/28800247-bb3e6cee-7600-11e7-944a-0d4ad05b39ab.png)

I also tried changing `style.less` on my Mac and got the same results - I cannot change the font. You mentioned that it works on your Mac so it sounds that I do something differently.... could it be some settings for the package?

**Comment by shd101wyy** [comment]
I would assume that this issue is caused by `fs.watch` function [(this line)](https://github.com/shd101wyy/mume/blob/master/src/mume.ts#L39).   
For your case, you can try restarting atom, and then it should take effect.  
I will try to fix it in next release.    

Thank you

**Comment by dzmitryv** [comment]
Did you mean that I need to restart Atom after editing `style.less`? If so, that didn't help (on Ubuntu).

**Comment by shd101wyy** [comment]
GG, I will try to fix it in next release.

**Comment by dzmitryv** [comment]
It works! I've tested on Ubuntu and Mac that code below affects both font size and background color:
```
html body {
  .preview {
    font-size:8px;
    background-color: blue;
  }
  .mume {
    .preview() !important;
  }
}
```

If background-color is inside .reveal or .slides it doesn't change anything. If !important commented out, the font doesn't change but background color is still being affected.

Thank you!

**Comment by shd101wyy** [comment]
@dzmitryv I think I will need to update the documentation :)

**Comment by shd101wyy** [comment]
@dzmitryv now the following should work:  

```less
.markdown-preview.markdown-preview {
  font-size: 8px; // your code...
}
```
