### ISSUE TITLE
怎么更改presentation的theme

### ISSUE THREAD

**Issue by fcui** [shd101wyy/markdown-preview-enhanced#492]
找不到更改theme的设定, 好像只能是白底黑字

**Comment by shd101wyy** [comment]
改 preview theme 可以。

**Comment by fcui** [comment]
这几个我已试过. 但不知道有没办法试试reveal js本来的几个的theme, 不过这个不是急需的. 如果可以就最好.

**Comment by shd101wyy** [comment]
@fcui [vscode 版本](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) 支持原声的 revealjs 主题了，你可以先试试。Atom 版本会随后跟进。  

![screen shot 2017-07-12 at 5 11 20 pm](https://user-images.githubusercontent.com/1908863/28142149-395578ce-6725-11e7-9734-ac1e6ff21a80.png)
![screen shot 2017-07-12 at 5 11 57 pm](https://user-images.githubusercontent.com/1908863/28142153-3b0bbc46-6725-11e7-9d07-fe8d05eb478f.png)

**Comment by fcui** [comment]
已经可以用了, 这么快就解决了, 非常感谢. 现在唯一的问题就是reveal js的主题没一个是居左的, 但这好像不是你的问题了.

**Comment by shd101wyy** [comment]
@fcui 这个简单，直接 `Markdown Preview Enhanced: Customize CSS` 然后

```less

body {
  // modify your style here
  // eg: background-color: blue;
  // background-color: blue;
  text-align: left;
  h1, h2, h3, h4, h5, h6, p, section {
    text-align: left;
  }
}    
```
