### ISSUE TITLE
plantuml activity diagram horizontally compressed

### ISSUE THREAD

**Issue by ketigid** [shd101wyy/markdown-preview-enhanced#493]
I am experimenting with this plantuml code to see how a very wide diagram is handled.
The resulting diagram is horizontally compressed and the text is not readable, i.e. the aspect ratio was not preserved.

How do I preserve the aspect ratio of the diagram?

```plantuml
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA->BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA->CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC->AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

**Comment by shd101wyy** [comment]
@ketigid Try `Markdown Preview Enhanced: Customize Css` then edit:

```less
.markdown-preview-enhanced.markdown-preview-enhanced {
    svg {
        max-width: none;
    }
}
```
