### ISSUE TITLE
幻灯片怎么修改字体大小

### ISSUE THREAD

**Issue by shangguanfch** [shd101wyy/markdown-preview-enhanced#505]
如题。0.14的字比旧版本大太多了。

**Comment by shd101wyy** [comment]
Markdown-preview-enhanced: customize css 命令然后修改 css。
关于幻灯片的 css 遵循了 revealjs 官方的 theme。你可以去它的官网看看

**Comment by shd101wyy** [comment]
例如 

```less
html body {
  .reveal {
    font-size: 32px;
  }
}
```
