### ISSUE TITLE
中文导出pdf出错

### ISSUE THREAD

**Issue by icysunlight** [shd101wyy/markdown-preview-enhanced#507]
atom:1.18.0
markdown-preview-enhanced:0.14.2

使用pandoc导出pdf报错：unicode char not set up for use to latex
![image](https://user-images.githubusercontent.com/12060699/28298863-55a9de20-6ba8-11e7-83e0-262dd1134416.png)
这样修改后也不好用，请问该怎么修改呢？
这是我的配置：
![image](https://user-images.githubusercontent.com/12060699/28298908-9a95bb76-6ba8-11e7-9277-129aa77f976a.png)

另外使用dot生成的图片使用哪种导出pdf的方式可以在生成的文件中显示出来呢？
非常感谢

**Comment by shd101wyy** [comment]
关于中文我没有尝试过这个周末我看下吧。dot 图像不应该有问题的，但是你可以 open in browser 然后右键菜单 print 为 pdf

**Comment by gepcel** [comment]
Try this:

```yaml
---
output:
    pdf_document:
        latex_engine: xelatex
CJKmainfont: Source Han Serif CN
CJKmonofont: FangSong
CJKoptions: ItalicFont=KaiTi
---
```

字体改为你喜欢的并且系统里面有的。系统里要有可用的 tex，如 MiKTex (for windows) , or texlive.
