### ISSUE TITLE
通过prince转换pdf后文字超出页面

### ISSUE THREAD

**Issue by lq0607** [shd101wyy/markdown-preview-enhanced#509]
我用prince将markdown文件转成pdf后，有部分文字超出了页面。
![image](https://user-images.githubusercontent.com/6753623/28302902-b82277fa-6bc2-11e7-9178-276e4b30164d.png)
请问是我设置有问题吗？或者能否自动或者手动选择适合的页面尺寸？谢谢

**Comment by shd101wyy** [comment]
@lq0607 这应该是 `prince` 的 style 的问题。
你可以运行命令 `Markdown Preview Enhanced: Customize CSS` 然后编辑 `style.less` 文件如下：

```less
html body {
  // prince 的样式
  &.prince {
    ul, ol {
      margin: 0;
    }
  }
}
```
