### ISSUE TITLE
建议: Preview界面的TOC可以做到浮空吗?

### ISSUE THREAD

**Issue by hhysj** [shd101wyy/markdown-preview-enhanced#526]
Preview界面的TOC可以做到浮空吗? 
基本上开预览的时候, 左右2个屏勉强够用了, 再打开旁边的TOC, 预览界面太窄了.
拜谢大神!

**Comment by shd101wyy** [comment]
大兄弟可否来张示意图。    
还有我觉得做成浮空的话，会遮挡原来的内容吧。    
我有时间了周末研究一下。    
谢谢 :)

**Comment by hhysj** [comment]
@shd101wyy 
![image](https://user-images.githubusercontent.com/5062393/28579352-05fbfc22-718f-11e7-8c6c-8d797e42de70.png)

类似于minimap的`absolute-mode`，不压缩预览页的空间。

**Comment by cnin** [comment]
楼主的目录是用mpe生成的吗 
在右边显示目录很实用 如果不是mpe的话 能否告知是用的什么previewer呢

**Comment by shd101wyy** [comment]
@hhysj 如果你只是想要不压缩空间的话，可以通过 `Markdown Preview Enhanced: Customize Css` 命令代开 `style.less` 文件，然后编写如下：

```less
html, body {
  .mume {
    width: 100% !important;
  }

  .md-sidebar-toc {
    z-index: 999 !important;
    background-color: inherit;
  }
}
```

![screen shot 2017-07-26 at 1 28 15 pm](https://user-images.githubusercontent.com/1908863/28637192-4d2cbbf0-7206-11e7-9d4e-21abaa717dab.png)
