### ISSUE TITLE
如何改变code block字体?

### ISSUE THREAD

**Issue by Jasper0819X** [shd101wyy/markdown-preview-enhanced#527]
如题。
version: 0.14.3
atom: 1.18.0 x64

**Comment by shd101wyy** [comment]
正好今晚失眠了。  
你可以运行 `Markdown Preview Enhanced: Customize Css` 命令，打开并编辑 `style.less` 文件：  

![screen shot 2017-07-25 at 2 46 10 am](https://user-images.githubusercontent.com/1908863/28561305-82822b38-70e3-11e7-8e0e-aec1faa9ac66.png)

例如上面的截图使用了 google font  中的 `Indie Flower` 字体。  

```less
html body {
  code[class*="language-"], 
  pre[class*="language-"] {
    font-family: 你的字体;
  }
}
```
