### ISSUE TITLE
更新后，自定义CSS无法调整字体大小

### ISSUE THREAD

**Issue by iDragonfly2050** [shd101wyy/markdown-preview-enhanced#538]
```
html body {
	// modify your style here
	// eg: background-color: blue;
	font-size: 20px;
	font-family: "新宋体";

	h1 {
		border-bottom: 1px solid #999999;
		font-family: "微软雅黑";
	}
}
```

`h1`和`p`的字体大小都能生效，但是调整`body`字体大小没有效果。

**Comment by iDragonfly2050** [comment]
可以使用`Ctrl + =`和`Ctrl + -`调整，但是没有记忆效果，重新打开以后还是默认的字体大小。

**Comment by shd101wyy** [comment]
重启 atom 呢？

**Comment by shd101wyy** [comment]
嗯确实有问题，我找时间修下。

**Comment by shd101wyy** [comment]
现在还没有写记忆效果的功能。

**Comment by shd101wyy** [comment]
@iDragonfly2050 我修改了下逻辑，原来的 `html body` 并不是很好，现在请写成这样 

```less
.markdown-preview.markdown-preview {
	// modify your style here
	// eg: background-color: blue;
	font-size: 20px;
	font-family: "新宋体";

	h1 {
		border-bottom: 1px solid #999999;
		font-family: "微软雅黑";
	}
}
```
