### ISSUE TITLE
Github styles seem to have changed

### ISSUE THREAD

**Issue by jmatsushita** [shd101wyy/markdown-preview-enhanced#552]
Hi there,

It seems that the github styles have changed. It used to have a  ```border-bottom: 1px solid #eaecef;
```  for `h1` and `h2` but they don't seem to be here anymore in the `github-light.css` preview style or the dark one neither.

Would it be possible to get back a style that's as close as possible to github's styles?

Thanks!

Jun

**Comment by shd101wyy** [comment]
You can put it back by customizing CSS.

**Comment by shd101wyy** [comment]
Run `Markdown Preview Enhanced: Customize Css` command, then edit `style.less` file like below:  

```less
.markdown-preview.markdown-preview {
  h1, h2, h3 {
    border-bottom: 1px solid #ccc;
  }
}
```
