### ISSUE TITLE
unicode char ภ not set up for use with LaTex

### ISSUE THREAD

**Issue by xu4wang** [shd101wyy/markdown-preview-enhanced#574]
Hi All,

I am trying to convert one markdown file into pdf using pandoc. There are some paragraph in Thai in the markdown file.

The convertion is not sucessful with the error below:
```
Error: Command failed: pandoc -f markdown+tex_math_single_backslash -o /Users/wangxu/CloudStation/gollum_wiki/atom/assets/VOA_Flow_Thai.pdf --toc --number-sections --latex-engine=pdflatex ! Package inputenc Error: Unicode char ภ (U+E20) (inputenc) not set up for use with LaTeX.

See the inputenc package documentation for explanation. Type H for immediate help. ...

l.112 ภ

Try running pandoc with --latex-engine=xelatex. pandoc: Error producing PDF

```

It may not be a MPE issue, but do  you know how to follow the suggestion and add a parameter to pandoc?

```
--latex-engine=xelatex
```

**Comment by xu4wang** [comment]
Tried adding latex-engine in the output section:
```
title: "Flow Chart"
geometry: margin=3cm
output:
  pdf_document:
    path: /assets/Flow_Thai.pdf
    toc: true
    number_sections: true
    latex-engine: xelatex
```

Still complaining, seems it's still using pdflatex as latex engine.

```
Error: Command failed: pandoc -f markdown+tex_math_single_backslash -o /Users/wangxu/CloudStation/gollum_wiki/atom/assets/VOA_Flow_Thai.pdf --toc --number-sections --latex-engine=pdflatex ! Package inputenc Error: Unicode char ภ (U+E20) (inputenc) not set up for use with LaTeX.
```

**Comment by xu4wang** [comment]
```
output:
  pdf_document:
    latex_engine: xelatex
```
but the Thai Character is not displayed correctly.   I'm giving up pdf. Will use html instead.

![snip20170817_4](https://user-images.githubusercontent.com/311397/29373495-080befc8-82e1-11e7-9852-9d77a64bfb3a.png)

**Comment by xu4wang** [comment]
今天试了下pandoc生成的中文pdf也不能显示，似乎需要加上font才行。 请问下frontmatter里面能配置下面的variable吗？ @shd101wyy 

‘’‘
--variable sansfont="Helvetica" --variable monofont="Menlo" 
’‘’

**Comment by adayone** [comment]
同 编译可以通过

**Comment by xu4wang** [comment]
能生成pdf，但是里面的中文都看不到。

估计pandoc命令行配置配置可以解决。 求熟悉pandoc的同学支持。

**Comment by xu4wang** [comment]
通过下面的workaround解决了中文显示问题。

```
output:
  pdf_document:
    latex_engine: xelatex
    path: /assets/pandoc_chinese.pdf
    toc: true
    number_sections: true
    pandoc_args:
        - '--variable'
        - mainfont="STHeiti-Light"
```

原因是MPE的setting里面的pandoc_args没有起作用。 需要在frontmatter里面手工设置。
