### ISSUE TITLE
导出html怎么进行设置呢？

### ISSUE THREAD

**Issue by Tarocch1** [shd101wyy/markdown-preview-enhanced#576]
导出html时，我希望去掉边栏目录，可是直接在md文件里写入

``` yaml
---
html:
  toc: false
---
```

没有效果。

此外，导出的html中代码块样式似乎默认是github-light，我在设置中已经设置为one-dark了，但是这个设置貌似只对预览有效果？
