### ISSUE TITLE
Todo check list items are not rendered as checkbox in ordered list

### ISSUE THREAD

**Issue by EnochLiou** [shd101wyy/markdown-preview-enhanced#592]
Hi, 

It seems a regression that the ordered list items are not rendered as checkbox style, while unordered list items converted correctly.

For example:

1. [ ] Undone item X
    * [ ] x
2. [x] Done item A
    * [x] alpha
    * [x] beta

![screenshot_checkbox_issue](https://user-images.githubusercontent.com/8587384/29552395-b0fb3d20-8749-11e7-9523-15c87beaafc7.png)

Despite of this tiny issue, markdown-preview-enhanced is still an excellent tool. Thank you ^_^

**Comment by shd101wyy** [comment]
Will be fixed in next release. Thanks for reporting that.

**Comment by shd101wyy** [comment]
@EnochLiou Fixed now. Thanks :)

**Comment by EnochLiou** [comment]
Hi, Yiyi,

Thank you, version 0.14.10 did fixed the issue. \^o^/

By the way, I also successfully made the lists having the prefixing numbering and/or marker 
by using atom-dark.css as Preview theme and importing customized CSS file.

A simple example for the customized CSS file may contain:

```css
html body ol li.task-list-item { list-style-type: decimal; }
html body ol li input.task-list-item-checkbox {
	margin: 0 0.1em 0.25em 0.2em;
	padding: 0;
}

html body ul li.task-list-item { list-style-type: circle; }
html body ul li input.task-list-item-checkbox {
	margin: 0 0.1em 0.28em 0.1em;
	padding: 0;
}

```

Note that the above CSS trick **only** worked for the following theme:

* auto.css
* atom-dark/light.css
* github-dark/light.css
* monokai.css
* one-dark/light.css
* solorized-dark/light.css

Hope this little trick could also benefit other fans of MPE.  :)

Have a nice day. ^_^
