### ISSUE TITLE
标题下划线的问题

### ISSUE THREAD

**Issue by HugSea** [shd101wyy/markdown-preview-enhanced#619]
刚下这款插件，我目前是默认不加下划线，并且手动设置的下划线好粗，如：
<img width="1141" alt="2017-09-17 2 46 45" src="https://user-images.githubusercontent.com/12068857/30518670-28d3ff9a-9bb7-11e7-9b10-c5194ad24253.png">

希望是标题默认加下划线，并且下划线的粗细和上下间距像下图一样：
![v2-72a8a1e742ffc030270e6dfd43d80a4c_r](https://user-images.githubusercontent.com/12068857/30518655-c11b4cbe-9bb6-11e7-9580-e1e36b087cb2.png)

请问作者该怎么改，麻烦了，非常感谢😭。

**Comment by shd101wyy** [comment]
https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/customize-css

**Comment by shd101wyy** [comment]
```less
.markdown-preview.markdown-preview {
  h1, h2, h3 {
    border-bottom: 1px solid #ccc;
  }
}
```

**Comment by HugSea** [comment]
感谢作者，好啦，但是我手动---加的下划线还是很粗，这个要怎么改呢

**Comment by shd101wyy** [comment]
你用上面那个就好了，不用手动加 `---` 下划线了。

**Comment by shd101wyy** [comment]
`---` 会生成 `hr` 元素，所以你就这么写就好了

```less
.markdown-preview.markdown-preview {
  hr {
    height: 0.1em;
  }
}
```
