### ISSUE TITLE
Fail to export word with reference.docx using Pandoc

### ISSUE THREAD

**Issue by HanInfinity** [shd101wyy/markdown-preview-enhanced#622]
front-matter in my.md:
```
---
title: "My title"
output:  
  word_document:
    reference_docx: reference.docx
    latex_engine: pdflatex
---
```
The reference.docx is in the same folder of my.md. It always failed when I right click on preview and use pandoc, and the message come out like this:
![image](https://user-images.githubusercontent.com/5977351/30735158-857d09ec-9fb0-11e7-8710-eee7a88e3152.png).

The pandoc is worked when I delete "reference_docx: reference.docx", but using reference.docx will make it better!!

**Comment by shd101wyy** [comment]
@HanInfinity My bad.

It is a bug one [this line](https://github.com/shd101wyy/mume/blob/master/src/pandoc-convert.ts#L43).  
The `--reference_docx` should be `--reference-docs` instead.  
Right now you can resolve this issue by writing it as:

```
title: "My title"
output:  
  word_document:    
    reference_docx: reference.docx
    latex_engine: pdflatex
    pandoc_args: ["--reference-docs=custom-reference.docx"]
```

Thanks

**Comment by HanInfinity** [comment]
@shd101wyy
 Thanks for your reply!

But it didn't worked, so I changed some word and it worked great!
It is:
```
---
title: "My title"
output:  
  word_document:
    reference-docx: reference.docx
    latex_engine: pdflatex
    pandoc_args: ["--reference-docx=reference.docx"]
---
```

and thank you again!
