### ISSUE TITLE
Cann't apply the  'reference-doc' arg.

### ISSUE THREAD

**Issue by gepcel** [shd101wyy/markdown-preview-enhanced#629]
For some reason I use pandoc 2.0, and the right arg for style referencing is "reference-doc=FILE" instead of "reference-docx=FILE". So I use `pandoc_args` in front-matter like:
```yaml
---
output:
    word_document:
        pandoc_args: [
        "reference-doc": "style.docx"
        ]
---
```

It used to work (a few months ago, cann't remember the version), but now it doesn't. Gives me a "Output format needs to be specified." error.

Would you please check this?

**Comment by shd101wyy** [comment]
"--reference-doc=file" or "--reference-docx=file"? Now you are writing
object inside array, I think it failed to parse.

**Comment by shd101wyy** [comment]
https://github.com/shd101wyy/markdown-preview-enhanced/issues/622

**Comment by gepcel** [comment]
## First
I tried 
```
---
output:
  word_document:
    pandoc_args: [
      "--reference-doc", "style.docx"
    ]
---


# head1

## head2

```
And I got `Output format needs to be specified.`

## Second
And tried 
```
---
output:
  word_document:
    pandoc_args: [
      "--reference-doc=style.docx"
    ]
---


# head1

## head2

```

Still got `Output format needs to be specified.`.  This used to work.

## Third
```
---
output:
  word_document:
    reference_docs: style.docx
---

# head1

## head2
```
Can get an output, but the style isn't applied.

## Fourth
```
---
output:
  word_document:
    reference_doc: style.docx
---

# head1

## head2
```
Can get an output, but the style isn't applied.

## Fifth
```
---
output:
  word_document:
    reference_docx: style.docx
---

# head1

## head2
```
Get an error message:
```
Error: Command failed: D:\Program Files (x86)\Pandoc\pandoc.exe -f markdown+tex_math_single_backslash -o D:\test.docx --reference_docx=style.docx --latex-engine=pdflatex Unknown option --reference_docx=style.docx. Try pandoc.exe --help for more information.
```

I expect the 2nd and the 5th to work. And the 2nd used to work a few months ago.
