### ISSUE TITLE
MathJax in phantomjs export very small

### ISSUE THREAD

**Issue by fibis** [shd101wyy/markdown-preview-enhanced#678]
When I export my document via PhantomJS -> PDF is there a problem with MathJax export. The font is really small compared to the other letters:
![screenshot_11](https://user-images.githubusercontent.com/7265809/32438602-613bbffc-c2eb-11e7-9051-da67bbba40d4.png)
With KaTex is there no problem.

**Comment by shd101wyy** [comment]
@fibis I will have a look when I have time. Thanks.

**Comment by merz9b** [comment]
@fibis I think you could toggle `ctrl+shift+p` select the Customize Css, add the following codes into the file:
```css
  .markdown-preview.markdown-preview {

  //custom phantomjs pdf export style
  &.phantomjs-pdf {
    // 你的代码
    .MathJax {font-size: 40px}
  }
}
```
You could replace 40px to the size you like.
