### ISSUE TITLE
[QUESTION] Is there a way to specify the title of TOC?

### ISSUE THREAD

**Issue by gepcel** [shd101wyy/markdown-preview-enhanced#688]
When exporting a file to pdf by through pandoc like this:
```yaml
---
output:
    pdf_document:
        latex_engine: xelatex
        number_sections: true
        toc: true
---
```
or a word file like this:
```yaml
---
output:
  word_document:
    toc: true
---
```
I will get a pdf file with a TOC. The title (caption) of the TOC is "Contents"
Or a docx file with TOC, the title (caption) of which is "Table of Contents"

Is there a way I can change that to others (目录 for example)?
