### ISSUE TITLE
how to fix font size for printing when "open in Browser"

### ISSUE THREAD

**Issue by paskaly** [shd101wyy/markdown-preview-enhanced#738]
Hi,
I'm using a 4K monitor and the font preview, with default font size, is very very small.
I can set bigger font size in preview modifying the `style.less` file in the `.markdown-preview.markdown-preview` section. 
To see an readble text, I have to set at least 18 pt font size. But when I click on 'open in Browser' the new big size is reflected in the browser and I cannot print with this big fonts.
I have tried to set the size even in @media print {} but with no results.
Any suggestion?
Thanks,

**Comment by shd101wyy** [comment]
Can I see your style.less file? Thanks

**Comment by paskaly** [comment]
Sure :)
various attempt commented ...
Thanks,
--------------

html body {
  // modify your style here
  // eg: background-color: blue;
  font-family: "Geneva", "Avenir Next Condensed", "Helvetica Neue",
"Liberation Sans", "DejaVu Sans";
  // font-size: 24px;
}

h1 {
  border-bottom: 1px solid;
  border-color: blue;
  padding-bottom: 0;
}

h2 {
  padding-bottom: 0;
  margin-top: 0.5em;
  margin-bottom: 0.1em;
  color: red;
}

/*
 * Code Section
 */
code {
  font-family: "Anka/Coder Condensed", "Liberation Mono", "DejaVu Sans
Mono", "Menlo" !important;
    font-size:14px;
    background-color:#f8f8ff;
    color:#444;
    padding:0 .2em;
    border:1px solid #dedede;
}

pre {
  font-family: "Anka/Coder Condensed", "Liberation Mono", "DejaVu Sans
Mono", "Menlo" !important;
    margin:1em 0;
    font-size:14px;
    background-color:#BCB6B6;
    // border:1px solid #A94141;
    padding:5px;
    line-height:1.5em;
    color:#444;
    overflow:auto;
    -webkit-box-shadow:rgba(0,0,0,0.07) 0 1px 2px inset;
    -webkit-border-radius:4px;
    -moz-border-radius:4px;
  border-radius:4px;
    border-left-width: 3px;
    border-left-color: blue;
    white-space: pre-wrap;
    word-wrap: break-word;
}

pre code {
    padding:0;
    font-size:12pt;
    border:none;
    /* color: #4444ff; */
}

// useless ...
@media print {
  font-family: Cambria, "Liberation Sans", "DejaVu Sans";
  font-size:10px !important;

}

.markdown-preview.markdown-preview {
  // please write your custom style here
  // eg:
  //  color: blue;          // change font color
  //  font-size: 12px;      // change font size
  // custom pdf output style
  font-family: "Avenir Next Condensed", "Helvetica Neue", "Liberation
Sans", "DejaVu Sans";
  font-size: 12pt;
  // zoom is useless ... shows just for a instast and then reverts to small
  zoom: 1.5;

  h2, h3, h4, h5 {
    padding-bottom: 0.2em;
    margin-top: 0.5em;
    margin-bottom: 0;
  }



  @media print p{
    font-family: "Avenir Next Condensed", "Liberation Sans", "DejaVu Sans";
    font-size:10px !important;

  }

  // no ... does not exists a such configuration
  &.browser {
    font-size: 8pt;
  }

  // custom prince pdf export style
  &.prince {
  }

  // custom phantomjs png/jpeg export style
  &.phantomjs-image {
  }

  //custom phantomjs pdf export style
  &.phantomjs-pdf {
  }

  // custom presentation style
  .reveal .slides {
    // modify all slides
  }

  .slides > section:nth-child(1) {
    // this will modify `the first slide`
  }
}

.md-sidebar-toc.md-sidebar-toc {
  // sidebar TOC style
}


--------------

**Comment by paskaly** [comment]
Voila' :)

```css
html body {
  // modify your style here
  // eg: background-color: blue;
  font-family: "Geneva", "Avenir Next Condensed", "Helvetica Neue",
"Liberation Sans", "DejaVu Sans";
  // font-size: 24px;
}

h1 {
  border-bottom: 1px solid;
  border-color: blue;
  padding-bottom: 0;
}

h2 {
  padding-bottom: 0;
  margin-top: 0.5em;
  margin-bottom: 0.1em;
  color: red;
}

/*
 * Code Section
 */
code {
  font-family: "Anka/Coder Condensed", "Liberation Mono", "DejaVu Sans Mono", "Menlo" !important;
    font-size:14px;
    background-color:#f8f8ff;
    color:#444;
    padding:0 .2em;
    border:1px solid #dedede;
}

pre {
  font-family: "Anka/Coder Condensed", "Liberation Mono", "DejaVu Sans Mono", "Menlo" !important;
    margin:1em 0;
    font-size:14px;
    background-color:#BCB6B6;
    // border:1px solid #A94141;
    padding:5px;
    line-height:1.5em;
    color:#444;
    overflow:auto;
    -webkit-box-shadow:rgba(0,0,0,0.07) 0 1px 2px inset;
    -webkit-border-radius:4px;
    -moz-border-radius:4px;
  border-radius:4px;
    border-left-width: 3px;
    border-left-color: blue;
    white-space: pre-wrap;
    word-wrap: break-word;
}

pre code {
    padding:0;
    font-size:12pt;
    border:none;
    /* color: #4444ff; */
}

// useless ...
@media print {
  font-family: Cambria, "Liberation Sans", "DejaVu Sans";
  font-size:10px !important;

}

.markdown-preview.markdown-preview {
  // please write your custom style here
  // eg:
  //  color: blue;          // change font color
  //  font-size: 12px;      // change font size
  // custom pdf output style
  font-family: "Avenir Next Condensed", "Helvetica Neue", "Liberation Sans", "DejaVu Sans";
  font-size: 12pt;
  // zoom is useless ... shows just for a instast and then reverts to small
  zoom: 1.5;

  h2, h3, h4, h5 {
    padding-bottom: 0.2em;
    margin-top: 0.5em;
    margin-bottom: 0;
  }

  @media print {
    font-family: "Avenir Next Condensed", "Liberation Sans", "DejaVu Sans";
    font-size:10px !important;
  }

  // no ... does not exists a such configuration
  &.browser {
    font-size: 8pt;
  }

  // custom prince pdf export style
  &.prince {
  }

  // custom phantomjs png/jpeg export style
  &.phantomjs-image {
  }

  //custom phantomjs pdf export style
  &.phantomjs-pdf {
  }

  // custom presentation style
  .reveal .slides {
    // modify all slides
  }

  .slides > section:nth-child(1) {
    // this will modify `the first slide`
  }
}

.md-sidebar-toc.md-sidebar-toc {
  // sidebar TOC style
}
```

**Comment by shd101wyy** [comment]
You should delete `html body` section. That is deprecated now.
Write everything inside `.markdown-preview.markdown-preview`. 
Then change your `font-size: 12pt` to `font-size: 18px`. (It is recommended to use `px` instead of `pt`).
Thanks

**Comment by paskaly** [comment]
Hi, sorry for the absence ...
I tried all the modication: those works for the view size, but the print font size is still too big. In other words, the modification in 
```css
.markdown-preview.markdown-preview {
  font-family: "Avenir Next Condensed", "Helvetica Neue", "Liberation Sans", "DejaVu Sans";
  font-size: 22px;
```
is reflected also in the `Open in Browser`. 
**My goal is to have a font for the view in Atom or VSCode and a different font size for printing** I use `open in browser` command to print the `.md` file.
For now, I'm using a workaround: when I have to print, I need to scale the output from Firefox.
the  `@media print` has no effect on the `open in browser` results
```css
  @media print p {
    font-family: "Avenir Next Condensed", "Liberation Sans", "DejaVu Sans";
    font-size:8px !important;
  }
```
Any suggestion?
Thanks,
