### ISSUE TITLE
如何修改公式的字体大小？

### ISSUE THREAD

**Issue by LiSikaiUSTB** [shd101wyy/markdown-preview-enhanced#746]
现在公式比文字稍微大一点，想要调成一样大的该怎么做？

**Comment by shd101wyy** [comment]
先运行 Markdown-Preview-Enhanced: Customize Css 命令打开 style.less。
如果你使用的是 `KaTeX` 渲染数学符号，你需要编辑 style.less 如下:

```less
.markdown-preview.markdown-preview {
  .katex {
    font-size: 24px; // <= font size here
  }
}
```

如果你用的是 MathJax，需要编辑如下：

```less
.markdown-preview.markdown-preview {
  .mathjax-exps {
    font-size: 32px; // <= font size here
  }
}
```

谢谢
