### ISSUE TITLE
引入的代码块过长的话，会显示滚动条，怎么让其在打印的时候不显示滚动条能看到完整代码呢

### ISSUE THREAD

**Issue by lightlogic5** [shd101wyy/markdown-preview-enhanced#819]
引入的代码块过长的话，会显示滚动条，怎么让其在打印的时候不显示滚动条能看到完整代码呢

**Comment by shd101wyy** [comment]
Hi @lightlogic5 ，把你的文件发我看看？

**Comment by lightlogic5** [comment]
@shd101wyy 谢谢你的回复，就像这样

**Comment by lightlogic5** [comment]
@shd101wyy 谢谢你的回复，就像这样

**Comment by shd101wyy** [comment]
@lightlogic5 抱歉我回复你晚了。
你可以 `cmd+shift+p` 运行 `Markdown Preview Enhanced: Customize Css` 命令打开 `style.less` 文件，然后编写如下

```less
.markdown-preview.markdown-preview {
    // 如果你想要预览也没有滚动条
    pre {
      white-space: pre-wrap;
      word-break: break-all;
    }

     // 这面的是打印用的
    @media print {
      pre {
        white-space: pre-wrap;
        word-break: break-all;
      }
  }
}
```
