### ISSUE TITLE
Unable to style body{} with Prince

### ISSUE THREAD

**Issue by ExCrusader** [shd101wyy/markdown-preview-enhanced#881]
Hi, I am unable to style the body tag just in Prince to export a two-column pdf, but I am able to style it overall. I am editing my ~/.mume/style.less file.

This doesn't work:
```css
/* Please visit the URL below for more information: */
/*   https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css */

.markdown-preview.markdown-preview {
   &.prince {


      body {
        column-count: 2;
      }
   }
}
```
But if I comment out the Prince specific parts if does export two columns, but it is two columns everywhere else as well. I want two-column text to be specific to the Prince pdf.
```css
/* Please visit the URL below for more information: */
/*   https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css */

/*.markdown-preview.markdown-preview {
   &.prince {*/


      body {
        column-count: 2;
      }
/*   }
}*/
```
Any ideas on how to fix this problem?

Thank you.
