### ISSUE TITLE
how to get black preview style ?

### ISSUE THREAD

**Issue by yushukk** [shd101wyy/markdown-preview-enhanced#89]
![image](https://cloud.githubusercontent.com/assets/2902100/17243819/384cea42-55b1-11e6-8d3a-70fd6935e9b0.png)
The h1 --> font color can not default.

**Comment by shd101wyy** [comment]
Hi @yushukk ,

This package by default is using github style.
If your **Atom** editor is currently in black style, then you can open `Settings View`, find `Markdown Preview Enhanced` package, then enter `Settings`.  You need to disable `Use Github.com style`. Then the preview style will be consistent with your **Atom** editor style.

![screen shot 2016-07-29 at 5 26 46 pm](https://cloud.githubusercontent.com/assets/1908863/17243927/c749c486-55b1-11e6-99e5-5c298ff68d61.png)  

---

Another way is to customize css. However, this method is more complicated.  
You can `cmd+shift+p` then choose `Markdown Preview Enhanced: Customize Css`.
It will open `style.less` for you.   
Then you can edit `.markdown-preview-enhanced-custom` section like this:
```less
/*
 * markdown-preview-enhanced custom style
 */
.markdown-preview-enhanced-custom {
  // please write your custom style here
  // eg:
  //  color: blue;          // change font color
  //  font-size: 14px;      // change font size
  //

  background-color: black;  // your background color
  color: white;                       // your font color

  h1, h2, h3, h4, h5, h6, span {
    color: white;                     // your font color
  }

  // custom pdf output style
  @media print {
    font-size: 13px;
  }
}
```

Hope this helps ;)
