### ISSUE TITLE
customize the code block font size

### ISSUE THREAD

**Issue by pierrchen** [shd101wyy/markdown-preview-enhanced#895]
Hello,

Is there is a way to change the font size of the code block output? Thank you!

**Comment by shd101wyy** [comment]
`cmd-shift-p` then choose `Markdown Preview Enhanced: Customize Css` then modify `style.less` like below:

```less
.markdown-preview.markdown-preview {
  pre[data-role="codeBlock"] {
    font-size: 48px !important; // <= font size.
  }
}
```
