### ISSUE TITLE
本地图片嵌入html导出的问题

### ISSUE THREAD

**Issue by namettkk** [shd101wyy/markdown-preview-enhanced#921]
想把本地图片以 base64 格式嵌入html文档
```
---
html:
  embed_local_images: false
  embed_svg: true
  offline: false
  toc: undefined

print_background: false
---
```
请问这段代码应该在哪修改呢？插件设置里没有，把这段代码直接插入.md文件中也没用
